language: java
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_SDKS=sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a SKIN=WXGA800 LINT=true
  global:
    - TERM=dumb
    - secure: JSu0bJbR+ikwU7AdTfZtPDhTdKPKgdXkNLb3EyNwchJT1+o2/E0JnOi2T/hO+TKkGOv0r0RTcjapxuYOH1cGDy7zMfrHeSElMFyqO7ZjVCOhVH6ndjQrisqSUNMNZa39SDNH195DzGb9g160hWuK3cKWxHw6+m6wT11GHCeWN5I=
    - secure: CZ3B52muBIow9b1bhnNcLk1mSpHDAKgJx0IAq2IRjfC/p+LqlRicWO269n5jlRCQ0O6Nu5muzDvOS53YhyqEuOLnNcLv5XcBRdTyJ+OmvboqJEbmX4T80ZfczkQXfO0Jub32vibRYlgp3/4Pm/hIV0tC7VbAijJHplLDXg7tpY0=

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - export COMPONENTS=extra-android-m2repository,build-tools-19.0.3,android-19,$ANDROID_SDKS
  - curl -3L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

  # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin $SKIN
  #- emulator -avd test -no-audio -no-window &

before_script:
  # Make sure the emulator has started before running tests
  #- wait_for_emulator

install:
 - true

script:
  - sudo chmod +x gradlew
  #- ./gradlew connectedCheck

  - if [[ $LINT == 'true' ]]; then ./gradlew lint ; fi

after_success:
  - ./gradlew uploadArchives -PnexusUsername="${nexusUsername}" -PnexusPassword="${nexusPassword}"

notifications:
  email: false
